### ISSUE TITLE
Does it work with python 2?

### ISSUE THREAD

**Issue by cfingerh** [vintasoftware/django-celerybeat-status#6]

**Comment by hugobessa** [comment]
It should work @cfingerh. We still don't have a test suite to assure that (this is tracked on https://github.com/vintasoftware/django-celerybeat-status/issues/4).

Are you receiving any error?

**Comment by zhiyuli** [comment]
@hugobessa 
We are trying to integrate this lib into our django 1.11 + python 2.7 + celery4.1  project, but got this error.  Any suggestion would be appreciated. Thanks.

Internal Server Error: /admin/statuscheck/periodic-tasks/
Internal Server Error: /admin/statuscheck/periodic-tasks/
Traceback (most recent call last):
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/var/tethys_deploy/tethys/miniconda/envs/tethys/lib/python2.7/site-packages/celerybeat_status/views.py", line 17, in dispatch
    return super().dispatch(request, *args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by hugobessa** [comment]
@zhiyuli and @cfingerh I'm addressing this. Probably tomorrow we can have a new release fixing this bug.
